%import common.CNAME -> NAME
%import common.WS_INLINE
%import common.NEWLINE -> _NL
%ignore WS_INLINE

COMMENT: /#[^\n]*/
%ignore COMMENT

start: (_NL | stmt)*

stmt: const_stmt _NL*
    | law_stmt _NL*

const_stmt: "const" NAME "=" LINE_EXPR

law_stmt: "law" NAME "priority" PRIO _NL* "when" LINE_EXPR _NL* action_block "end"

action_block: action_line+
action_line: "do" ACTION_TEXT _NL*

PRIO: /[-0-9.]+/
LINE_EXPR: /[^\n#]+/
ACTION_TEXT: /[^\n#]+/

